<a href="https://colab.research.google.com/github/IBRHASHEM/llm-zoomcamp-2026-code/blob/main/Copy_of_Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class data:
  def __init__(self, student_name, age, subject):
    self.student_name=student_name
    self.age=age
    self.subject = subject
  def show(self):
    return self.student_name, self.age, self.subject

In [ ]:
student = data("Ibrahim", 25, "Python")
student.show()

('Ibrahim', 25, 'Python')

('email', 25, 'AI Engineer')

In [ ]:
import torch
import torch.nn as nn
x= torch.tensor([1.0,2.0,3.0])
print (x)
print (type[x])
y=torch.rand(3,3)
print (y)
print (y.shape)

tensor([1., 2., 3.])
type[tensor([1., 2., 3.])]
tensor([[0.8435, 0.9694, 0.7931],
        [0.7072, 0.7221, 0.4718],
        [0.3286, 0.3230, 0.9953]])
torch.Size([3, 3])


In [ ]:
class net:
  def __init__(self):
    self.layer1=nn.Linear(4,8)
    self.layer2=nn.ReLU()
    self.layer3=nn.Linear(8,1)
  def run(self, x):
    x=self.layer1(x)
    x=self.layer2(x)
    x=self.layer3(x)
    return x
net=net()

In [ ]:
input=torch.rand(1,4)
output=net.run(input)
print (output)

tensor([[-0.0607]], grad_fn=<AddmmBackward0>)
